export const AGENTS = {
  john: {
    name: "John",
    fullName: "John Lennon",
    model: "Kimi K2.5",
    philosophy: "The Oracle -- Value & Macro",
    color: "#f5a623",
    bgColor: "bg-yellow-950",
    borderColor: "border-yellow-700",
    deskItems: ["Buffett annual letters", "Intrinsic value calculator", "Guitar pick"],
    quote: "Be fearful when others are greedy...",
    instrument: "guitar",
    symbol: "glasses",
  },
  paul: {
    name: "Paul",
    fullName: "Paul McCartney",
    model: "GLM-5",
    philosophy: "The Strategist -- Institutional Analysis",
    color: "#a855f7",
    bgColor: "bg-purple-950",
    borderColor: "border-purple-700",
    deskItems: ["10-K filings", "Fund flow tracker", "Bass guitar"],
    quote: "Follow the smart money.",
    instrument: "bass",
    symbol: "notes",
  },
  george: {
    name: "George",
    fullName: "George Harrison",
    model: "DeepSeek V3.2",
    philosophy: "The Quant -- Probabilistic Reasoning",
    color: "#10b981",
    bgColor: "bg-emerald-950",
    borderColor: "border-emerald-700",
    deskItems: ["Z-score tables", "Base rate reference", "Sitar"],
    quote: "All things must pass... to the mean.",
    instrument: "sitar",
    symbol: "lotus",
  },
  ringo: {
    name: "Ringo",
    fullName: "Ringo Starr",
    model: "MiniMax M2.5",
    philosophy: "The Everyman -- Retail & Sentiment",
    color: "#3b82f6",
    bgColor: "bg-blue-950",
    borderColor: "border-blue-700",
    deskItems: ["Reddit feed", "Trending tickers", "Drumsticks"],
    quote: "What are people actually buying?",
    instrument: "drums",
    symbol: "stars",
  },
} as const;

export type AgentId = keyof typeof AGENTS;
export const AGENT_IDS = Object.keys(AGENTS) as AgentId[];
export const TICKERS = ["SPY", "NVDA", "GOOGL", "MU", "DJI", "GOLD"] as const;
